[project]
name = "quickshell-modules"
version = "0.1.0"
description = "QuickShell Python modules"
requires-python = ">=3.13"
dependencies = [
    "dbus-next>=0.2.3",
    "httpx>=0.28.1",
    "lunarcalendar>=0.0.9",
]
